id: P004395
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1017219
  title: གཏེར་མཛོད་ལོ་རྒྱུས་གཅེས་བཏུས་བློ་གསལ་དགྱེས་པའི་འཛུམ་ཟེར
  author: ''
  volumes:
    d6df493b751243b8973c999393cc57f7:
      image_group_id: I00EGS1017221
      title: ''
      volume_number: 1
      total_pages: 226
