id: P004395
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00EGS1017219
  title: གཏེར་མཛོད་ལོ་རྒྱུས་གཅེས་བཏུས་བློ་གསལ་དགྱེས་པའི་འཛུམ་ཟེར
  author: ''
  volumes:
    d6df493b751243b8973c999393cc57f7:
      image_group_id: I00EGS1017221
      title: ''
      volume_number: 1
      total_pages: 226
      base_file: v001.txt
