id: IA7C2FBA9
legacy_id: P004395
ocr_import_info:
  bdrc_scan_id: W00EGS1017219
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T15:42:42'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T03:23:04.318523+00:00'
last_modified: 2022-08-27 11:23:42.727085
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1017219
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1017219
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཏེར་མཛོད་ལོ་རྒྱུས་གཅེས་བཏུས་བློ་གསལ་དགྱེས་པའི་འཛུམ་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.893160410991033
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I00EGS1017221:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017221
      total_pages: 226
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00EGS1017221.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.893160410991033
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
